### ISSUE TITLE
Not locking up in Heroku

### ISSUE THREAD

**Issue by celine-m-s** [gblakeman/lockup#19]
Hello !

Many thanks for your gem, it works perfectly! Except it only work locally for me. When I deploy to Heroku, nothing is locked... I have a full access!
Could you tell me what I made wrong?
- Rails version: 4.2.0
- routes.rb: 
```ruby
Rails.application.routes.draw do

  # Beta Test
  mount Lockup::Engine, at: '/lockup'
...
end
```

- application.yml
  LOCKUP_CODEWORD: '<this is secret of course>'

Thanks!

Céline

**Comment by gblakeman** [comment]
Hi Céline, glad you like the gem.

I personally have minimal Heroku experience, but a couple things to double-check:

* Make sure the routes declaration is at the top of your routes file
* Make sure a codeword is defined (your example has it as an empty string): `LOCKUP_CODEWORD: 'something'`
* Since you are using `application.yml` instead of `secrets.yml`, make sure you have include the [figaro gem](https://github.com/laserlemon/figaro)
* If you have an [environment-specific configuration](https://github.com/laserlemon/figaro#environment-specific-configuration) of figaro, make sure you've declared `LOCKUP_CODEWORD` for production.

I'm also noticing some changes to figaro (I haven't kept up with it since I predominantly use Rails built-in `secrets.yml` now). It only works if the `LOCKUP_CODEWORD` parameter is uppercase and all of their examples are now lowercase in their docs. I should probably compensate for that in a future update.

Let me know if any of those more obvious tips help; if not, hopefully we can think of something else to try!

**Comment by gblakeman** [comment]
I just pushed a new version that now allows for lowercase Figaro definitions. I'm not sure if that was part of your issue at all, but it might now hurt to try with the new update:

`gem 'lockup', '~> 1.3.2'`

**Comment by celine-m-s** [comment]
Hello !
Thank you so much for answering that quickly! It seems to work because now I'm able to use it with Heroku, so this is perfect!
Do you know how I can customize the lockup page? Do I have to create a view 'unlock.html.erb' within a 'lockup' folder?
Thanks!
Céline

**Comment by gblakeman** [comment]
Awesome, glad it's working for you!

As far as customization, there isn't currently a supported provision for it, but you could certainly give it a shot! Add a view to `app/views/lockup/lockup/unlock.html.erb` using these views: https://github.com/gblakeman/lockup/tree/master/app/views/layouts/lockup as your starting point.

I've never tried this myself, so I'm not sure how it'll work!

You could also fork the gem and modify the templates directly, if you want.

**Comment by celine-m-s** [comment]
Hey!
I'll give it a try tonight and I'll tell you. Thanks!

**Comment by celine-m-s** [comment]
So far so good! It works perfectly. Thanks again for this awesome work!

**Comment by gblakeman** [comment]
Ha, awesome. Good idea! I hadn't even thought about trying that.
